- name: add ssh key for kronos
  authorized_key:
    user: kronos
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILh0Rsk/BAW8ZrXCHHE/5ytykUpWeYcs6+VK2godNIv0 ansible - for actually running ansible shit"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
